<!DOCTYPE html>
<html lang="en">    
    <head>
        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-SY91FB1KZ5"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-SY91FB1KZ5');
        </script>
        <title>DeadBeef | Home</title>
        <base href="/"> 
        <meta charset="UTF-8">
        <meta name="keywords" content="DeadBeef, Us ">
        <meta name="author" content="goussou0">
        <meta http-equiv="refresh" content="120"> <!-- update page every 30 seconds -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Welcome to deadbeef restaurant's website! Here you can learn about who we are and what we offer. enjoy your time in deadbeef and Satisfy your hunger with DeadBeef.">
        <!-- preload -->
        <link rel="preload" href="/static/css/styles.css" as="style">
        <link rel="preload" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" as="style">
        <!-- preload-->
        <link rel="stylesheet" href="/static/css/styles.css">
        <link rel="icon" type="image/x-icon" href="/static/img/favicon.ico">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" >
        <link rel="sitemap" type="application/xml" title="Sitemap" href="/static/sitemap.xml" >
        <link rel="apple-touch-icon" sizes="180x180" href="/static/img/apple-touch-icon.webp">
        <link rel="icon" type="image/webp" sizes="32x32" href="/static/img/favicon-32x32.webp">
        <link rel="icon" type="image/webp" sizes="16x16" href="/static/img/favicon-16x16.webp">
        <link rel="manifest" href="/static/site.webmanifest">
        <ul class="nav_lst" >
            <li class="nav_elm">
                <a href="/index.php">
                <img class="logo" src="/static/img/logo.svg" width="100" height="100"  alt="site logo" >
                </a>
            </li>
            <li class="nav_elm"><a class="item" href="/about.php">About Us</a></li>
            <li class="nav_elm"><a class="item" href="/menu.php">Menu</a></li>
            <li class="nav_elm"><a class="item" href="/cart.php">Cart</a></li>
            <li class="nav_elm"><a class="item" href="/contact.php">Contact Us</a></li>
            <li class="nav_elm"><a class="item" href="/login.php">Login</a></li>
            <li class="nav_elm"><a class="item" href="/signup.php">Sign Up</a></li>
        </ul>  
    </head>
    <body>
    <?php
        session_start();
	    header("Cache-Control: max-age=31536000");
      	header("Age: 100");

      ?>
        <div class="card mt-1"> <!-- mt stands for margin top with 1rem-->
            <h1 class="card-header" style="margin:0 auto;font-size: 4rem;">Welcome</h1>
            <div class="card-bg">
                <img src="/static/img/Ceaser salad made from circut componants.webp" width="100" height="100"  alt='Ceaser salad made from circut componants' id="welcome-img" > 
            </div>
            <h2 style="margin:0 auto;font-size: 2rem;text-align: center;">  Satisfy your hunger with DeadBeef.</h2>
            <p style="text-align: center;">
            Welcome to our restaurant! We are a cozy and intimate dining establishment located in the heart of downtown. Our menu is generated by an AI, and features a wide range of dishes that are sure to please any palate.

Our menu is constantly evolving, as we strive to use the freshest and highest quality ingredients in all of our dishes. We believe that using the best ingredients is the key to creating truly delicious food, and we go to great lengths to source our ingredients from local farmers and producers.

In addition to our delicious food, we also offer an extensive selection of wines, beers, and cocktails to complement your meal. Our knowledgeable staff will be happy to help you choose the perfect beverage to pair with your food.

But what really sets us apart is the atmosphere and service at our restaurant. We have a warm and welcoming ambiance that makes our guests feel right at home. Our friendly and attentive staff will do everything they can to make sure you have a truly memorable dining experience.

So whether you're in the mood for a quick bite or a leisurely meal, we've got you covered. We hope to see you soon at our restaurant!We can't wait to see you at Deadbeef!
            </p>
            <div class="contacts">
                <!-- I will not share my social media accounts this will redirect to the sites -->
                <a href="https://twitter.com/" class="fa fa-twitter"></a>
                <a href="https://www.linkedin.com/" class="fa fa-linkedin"></a>
            </div>
        </div>
    </body>
</html>